// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwpakwktvyzusdieoqmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3cGFrd2t0dnl6dXNkaWVvcW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODU5MTUsImV4cCI6MjA2MTE2MTkxNX0.5VFZyLU0ZsRJtxgswmSRYkqcxL9FqeV-RZxRiwW3SZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);